# Copyright (C) 2025 Gil Benezer
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from . import base, builtin

# Base infrastructure
from .base import (  # Layer 3: Stochastic systems; Layer 2: Deterministic symbolic systems; Layer 4: Discretization; Layer 1: Abstract base classes; Submodules
    ContinuousDynamicalSystem,
    ContinuousStochasticSystem,
    ContinuousSymbolicSystem,
    ContinuousSystemBase,
    DiscreteDynamicalSystem,
    DiscreteStochasticSystem,
    DiscreteSymbolicSystem,
    DiscreteSystemBase,
    DiscretizationMode,
    DiscretizedSystem,
    StochasticDynamicalSystem,
    SymbolicDynamicalSystem,
    SymbolicSystemBase,
    analyze_discretization_error,
    compute_discretization_quality,
    core,
    discretize,
    discretize_batch,
    numerical_integration,
    recommend_dt,
    utils,
)

# Builtin systems
from .builtin import (  # Stochastic Continuous - Brownian motion; Deterministic Continuous - Cart-pole; Deterministic Continuous - Reactor systems; Stochastic Continuous - Reactor systems; Deterministic Continuous - Oscillators; Stochastic Continuous - Cox-Ingersoll-Ross process; Deterministic Discrete - Mobile robots; Stochastic Discrete - Time series models; Deterministic Discrete - Reactor systems; Stochastic Discrete - Financial models; Deterministic Discrete - Mechanical systems; Deterministic Discrete - Economic models; Stochastic Discrete - Reactor systems; Stochastic Discrete - Control systems; Stochastic Discrete - Nonlinear dynamics; Stochastic Discrete - Queueing systems; Stochastic Discrete - Multivariate models; Deterministic Continuous - Vehicles; Deterministic Continuous - Mechanical systems; Stochastic Continuous - Langevin dynamics; Deterministic Continuous - Linear systems; Deterministic Discrete - Chaotic maps; Deterministic Continuous - Chaotic systems; Stochastic Continuous - Ornstein-Uhlenbeck process; Stochastic Continuous - Control systems; Stochastic Continuous - Epidemiological models; Deterministic Continuous - Pendulum; Deterministic Continuous - Aerial systems; Submodules
    AR1,
    ARMA11,
    CIR,
    GARCH11,
    GBM,
    OU,
    PVTOL,
    SIR,
    VAR1,
    AutonomousLinearSystem,
    BrownianMotion,
    BrownianMotion2D,
    BrownianMotionWithDrift,
    CartPole,
    CartPoleSystem,
    ContinuousBatchReactor,
    ContinuousCSTR,
    ContinuousStochasticBatchReactor,
    ContinuousStochasticCSTR,
    ContinuousStochasticPendulum,
    ControlledLorenz,
    ControlledVanDerPolOscillator,
    CoupledOscillatorSystem,
    CoxIngersollRoss,
    DifferentialDriveRobot,
    DiscreteAR1,
    DiscreteARMA11,
    DiscreteBatchReactor,
    DiscreteCartPole,
    DiscreteCSTR,
    DiscreteDoubleIntegrator,
    DiscreteDoubleIntegratorWithForce,
    DiscreteGARCH11,
    DiscreteOscillator,
    DiscretePendulum,
    DiscreteRandomWalk,
    DiscreteRobotArm,
    DiscreteSolowModel,
    DiscreteStochasticBatchReactor,
    DiscreteStochasticCSTR,
    DiscreteStochasticDoubleIntegrator,
    DiscreteStochasticLogisticMap,
    DiscreteStochasticPendulum,
    DiscreteStochasticQueue,
    DiscreteVAR1,
    DiscreteWhiteNoise,
    DubinsVehicle,
    DuffingOscillator,
    FifthOrderMechanicalSystem,
    GeometricBrownianMotion,
    HenonMap,
    LangevinDynamics,
    LinearSystem,
    LinearSystem2D,
    LogisticMap,
    Lorenz,
    Manipulator2Link,
    MultivariateOrnsteinUhlenbeck,
    NonlinearChainSystem,
    OrnsteinUhlenbeck,
    PathTracking,
    PendulumSystem,
    RandomWalk,
    StandardMap,
    StochasticCartPole,
    StochasticDoubleIntegrator,
    StochasticLorenz,
    StochasticQueue,
    StochasticSIR,
    SymbolicPendulum,
    SymbolicPendulum2ndOrder,
    SymbolicQuadrotor2D,
    SymbolicQuadrotor2DLidar,
    VanDerPolOscillator,
    WhiteNoise,
    create_biased_random_walk,
    create_bivariate_var,
    create_call_center_queue,
    create_chaotic_regime,
    create_digital_servo,
    create_discrete_batch_reactor_with_noise,
    create_discrete_stochastic_cstr_with_noise,
    create_economic_arma,
    create_edge_of_chaos,
    create_equity_garch,
    create_fixed_point_regime,
    create_furuta_pendulum,
    create_fx_garch,
    create_lqg_benchmark_discrete,
    create_macro_var,
    create_measurement_noise,
    create_network_queue,
    create_rl_pendulum,
    create_sensor_arma,
    create_spacecraft_discrete,
    create_standard_white_noise,
    create_symmetric_random_walk,
    create_thermal_noise,
    deterministic,
    stochastic,
)

__all__ = [
    # Submodules
    "base",
    "builtin",
    "core",
    "numerical_integration",
    "utils",
    "deterministic",
    "stochastic",
    # Base - Abstract base classes
    "SymbolicSystemBase",
    "ContinuousSystemBase",
    "DiscreteSystemBase",
    # Base - Deterministic symbolic systems
    "ContinuousSymbolicSystem",
    "ContinuousDynamicalSystem",
    "SymbolicDynamicalSystem",
    "DiscreteDynamicalSystem",
    "DiscreteSymbolicSystem",
    # Base - Stochastic systems
    "ContinuousStochasticSystem",
    "StochasticDynamicalSystem",
    "DiscreteStochasticSystem",
    # Base - Discretization
    "DiscretizationMode",
    "DiscretizedSystem",
    "discretize",
    "discretize_batch",
    "analyze_discretization_error",
    "recommend_dt",
    "compute_discretization_quality",
    # Deterministic Continuous - Linear systems
    "LinearSystem",
    "AutonomousLinearSystem",
    "LinearSystem2D",
    # Deterministic Continuous - Pendulum
    "SymbolicPendulum",
    "SymbolicPendulum2ndOrder",
    "PendulumSystem",
    # Deterministic Continuous - Cart-pole
    "CartPole",
    "CartPoleSystem",
    # Deterministic Continuous - Aerial systems
    "SymbolicQuadrotor2D",
    "SymbolicQuadrotor2DLidar",
    "PVTOL",
    # Deterministic Continuous - Vehicles
    "DubinsVehicle",
    "PathTracking",
    # Deterministic Continuous - Oscillators
    "CoupledOscillatorSystem",
    "NonlinearChainSystem",
    "VanDerPolOscillator",
    "ControlledVanDerPolOscillator",
    "DuffingOscillator",
    # Deterministic Continuous - Chaotic systems
    "Lorenz",
    "ControlledLorenz",
    # Deterministic Continuous - Mechanical systems
    "FifthOrderMechanicalSystem",
    "Manipulator2Link",
    # Deterministic Continuous - Reactor systems
    "ContinuousBatchReactor",
    "ContinuousCSTR",
    # Deterministic Discrete - Mechanical systems
    "DiscreteOscillator",
    "DiscretePendulum",
    "DiscreteDoubleIntegrator",
    "DiscreteDoubleIntegratorWithForce",
    "DiscreteRobotArm",
    "DiscreteCartPole",
    # Deterministic Discrete - Mobile robots
    "DifferentialDriveRobot",
    # Deterministic Discrete - Reactor systems
    "DiscreteBatchReactor",
    "DiscreteCSTR",
    # Deterministic Discrete - Economic models
    "DiscreteSolowModel",
    # Deterministic Discrete - Chaotic maps
    "LogisticMap",
    "HenonMap",
    "StandardMap",
    # Stochastic Continuous - Brownian motion
    "BrownianMotion",
    "BrownianMotion2D",
    "GeometricBrownianMotion",
    "BrownianMotionWithDrift",
    "GBM",
    # Stochastic Continuous - Ornstein-Uhlenbeck process
    "OrnsteinUhlenbeck",
    "MultivariateOrnsteinUhlenbeck",
    "OU",
    # Stochastic Continuous - Cox-Ingersoll-Ross process
    "CoxIngersollRoss",
    "CIR",
    # Stochastic Continuous - Langevin dynamics
    "LangevinDynamics",
    # Stochastic Continuous - Control systems
    "StochasticDoubleIntegrator",
    "ContinuousStochasticPendulum",
    "StochasticCartPole",
    "StochasticLorenz",
    # Stochastic Continuous - Epidemiological models
    "StochasticSIR",
    "SIR",
    # Stochastic Continuous - Reactor systems
    "ContinuousStochasticBatchReactor",
    "ContinuousStochasticCSTR",
    # Stochastic Discrete - Time series models
    "DiscreteAR1",
    "AR1",
    "DiscreteWhiteNoise",
    "WhiteNoise",
    "create_standard_white_noise",
    "create_measurement_noise",
    "create_thermal_noise",
    "DiscreteRandomWalk",
    "RandomWalk",
    "create_symmetric_random_walk",
    "create_biased_random_walk",
    "DiscreteARMA11",
    "ARMA11",
    "create_economic_arma",
    "create_sensor_arma",
    # Stochastic Discrete - Multivariate models
    "DiscreteVAR1",
    "VAR1",
    "create_bivariate_var",
    "create_macro_var",
    # Stochastic Discrete - Financial models
    "DiscreteGARCH11",
    "GARCH11",
    "create_equity_garch",
    "create_fx_garch",
    # Stochastic Discrete - Control systems
    "DiscreteStochasticDoubleIntegrator",
    "create_digital_servo",
    "create_lqg_benchmark_discrete",
    "create_spacecraft_discrete",
    "DiscreteStochasticPendulum",
    "create_furuta_pendulum",
    "create_rl_pendulum",
    # Stochastic Discrete - Queueing systems
    "DiscreteStochasticQueue",
    "StochasticQueue",
    "create_call_center_queue",
    "create_network_queue",
    # Stochastic Discrete - Reactor systems
    "DiscreteStochasticBatchReactor",
    "DiscreteStochasticCSTR",
    "create_discrete_batch_reactor_with_noise",
    "create_discrete_stochastic_cstr_with_noise",
    # Stochastic Discrete - Nonlinear dynamics
    "DiscreteStochasticLogisticMap",
    "create_fixed_point_regime",
    "create_chaotic_regime",
    "create_edge_of_chaos",
]
